camera0: 1
camera1: 2
frame_width: 640
frame_height: 480
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 1.85
checkerboard_rows: 6
checkerboard_columns: 9
cooldown: 50